# services/github_service.py

from github import Github, GithubException
from config import config
from logger import get_logger
import base64

logger = get_logger(__name__)

# 🔥 INIT GITHUB CLIENT
g = Github(config.GITHUB_TOKEN)
repo = g.get_repo(config.GITHUB_REPO)


def create_branch(branch_name: str):
    """Create a new branch from base branch"""

    logger.info(f"Creating branch: {branch_name}")

    try:
        base_branch = repo.get_branch(config.GITHUB_BASE_BRANCH)

        repo.create_git_ref(
            ref=f"refs/heads/{branch_name}",
            sha=base_branch.commit.sha
        )

    except GithubException as e:
        # 🔥 If branch already exists, ignore
        if e.status == 422:
            logger.warning(f"Branch already exists: {branch_name}")
        else:
            logger.error(f"Branch creation failed: {e}")
            raise e


def commit_file(branch: str, path: str, content: str):
    """Create or update file in branch"""

    logger.info(f"Committing file: {path} on branch: {branch}")

    try:
        # 🔥 Check if file exists
        try:
            existing_file = repo.get_contents(path, ref=branch)

            # 🔥 UPDATE FILE
            repo.update_file(
                path=path,
                message=f"AI Update: {path}",
                content=content,
                sha=existing_file.sha,
                branch=branch
            )

            logger.info("File updated")

        except GithubException:
            # 🔥 CREATE NEW FILE
            repo.create_file(
                path=path,
                message=f"AI Create: {path}",
                content=content,
                branch=branch
            )

            logger.info("File created")

    except Exception as e:
        logger.error(f"Commit failed: {e}")
        raise e


def create_pr(branch: str) -> str:
    """Create pull request"""

    logger.info(f"Creating PR for branch: {branch}")

    try:
        pr = repo.create_pull(
            title=f"AI Generated Rule - {branch}",
            body="This PR was automatically generated by AI Rule Engine",
            head=branch,
            base=config.GITHUB_BASE_BRANCH
        )

        logger.info(f"PR created: {pr.html_url}")

        return pr.html_url

    except GithubException as e:
        logger.error(f"PR creation failed: {e}")
        raise e